version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    restart: unless-stopped
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: nikitarachkov1/kittygram_backend:latest
    env_file: .env
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - static:/app/static
      - media:/app/media

  frontend:
    image: nikitarachkov1/kittygram_frontend:latest
    restart: unless-stopped
    volumes:
      - static:/static

  gateway:
    image: nikitarachkov1/kittygram_gateway:latest
    restart: unless-stopped
    env_file: .env
    ports:
      - "9000:80"
    depends_on:
      - backend
    volumes:
      - static:/static
      - media:/media